# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3c69c591bbf3f79db76330bbb6dd11213e0769849fe928fb8ef1c00e98a7058fd7f872bf375f4f2d92596da13c99f4a425f14e7a4aba1023cfa4fc33ead97a0

test:
  secret_key_base: 09b8913e6dfda36715e5892204678da080bbd23b1d199c663d9a75b054659db7e9b9ee6159c2a3c603e5c3d71c56481ebd9e08287dc27a5f9ab40f0f416a0046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
